### ISSUE TITLE
Empty Internal transition

### ISSUE THREAD

**Issue by Lyadis** [SINTEF-9012/ThingML#102]
Is this code allowed in ThingML?

```
thing TestEmptyInternalTransition
{
	statechart TestEmptyInternalTransition init S1 {
		property i : UInt16 = '0'
	
		state S1 {
			on entry print "Start\n"
			internal
			guard i == 0
			action do
				print "Internal Empty transition\n"
				i = i + '1'
			end
			
			transition -> S2 guard not(i == 0)
		}


		state S2 {
			on entry print "Done\n"
		}
	}
}

datatype UInt16	
	@c_type "uint16_t"
	@c_byte_size "2"
	@java_type "int"
	@java_primitive "true";

configuration TestEmptyInternalTransitionCfg {
	instance  t:  TestEmptyInternalTransition
}
```
Because it works with the C compiler (State S2 is reached) 
but it doesn't with JS compiler (State S2 is never reached)
nor with the java compiler (Error at compilation of generated sources).

**Comment by brice-morin** [comment]
Yes, I guess it should be allowed. But not allowed (or discouraged if you do not have a guard, as it will loop forever).

**Comment by Lyadis** [comment]
In my opinion a warning is preferable to an error, as it can be the intended behaviour.

**Comment by brice-morin** [comment]
As for Javascript, I have to investigate a bit more, but it might be an issue in the JS library we are using, and we might need to contact the maintainer of that repo (who is typically quite responsive)

**Comment by brice-morin** [comment]
Confirmed issue in state.js library, see steelbreeze/state.js#22
