### ISSUE TITLE
Group support

### ISSUE THREAD

**Issue by Lyadis** [SINTEF-9012/ThingML#107]
Do we still want to support Configuration nested inside another configuration?

```
configuration NestedCfg
{
    ...
}

configuration Cfg
{
    group g : NestedCfg
    ...
}
```
Because it is still at the root of some bugs (See #26), and it makes both the ThingML and generated  code uglier and mroe confusing.

**Comment by Lyadis** [comment]
@ffleurey @brice-morin ?

**Comment by brice-morin** [comment]
I agree `group`s have many downsides. And I do not think they are used by our partners.

**Comment by ffleurey** [comment]
Agree as well.

**Comment by Lyadis** [comment]
Do you know who used the group notion? :-D ... Tests!!

**Comment by brice-morin** [comment]
Hehe... :-)

Should be easy to fix though

**Comment by brice-morin** [comment]
You mean the C tests, that use an old version of timer, that indeed relies on a configuration fragment to wrap the clock, etc.

**Comment by Lyadis** [comment]
Yes. But it is indeed an smal fix.
