### ISSUE TITLE
Regression in tests with c compiler

### ISSUE THREAD

**Issue by Lyadis** [SINTEF-9012/ThingML#112]
Some tests (testArrays, testArrays2, testMaskProperty) are not working anymore.

**Comment by brice-morin** [comment]
Yes. Seems like a general regression. I think I have similar problems in JS. Probably broke something with the latest modification of the metamodel

**Comment by Lyadis** [comment]
Ok 56d1012eb767213bda33c8ed850942e5eedc0503 fixes this issue.
