### ISSUE TITLE
Local tests are broken

### ISSUE THREAD

**Issue by brice-morin** [SINTEF-9012/ThingML#130]
It seems the local execution of the tests is broken. The ThingML files produced all contains error. Please fix ASAP

**Comment by Lyadis** [comment]
I don't have the problem on my machine with the latest commit... What kind of errors are you dealing with?

**Comment by brice-morin** [comment]
Seems like the problem is that it generate one absolute path with `\` on Windows, for one of the import, and that it does not parse correctly. Something like: `import "C:\Users\xxx\ThingML\testJar\src\main\resources\tests\StateMachine\testCompositeStates.thingml"`

**Comment by brice-morin** [comment]
Something like `import "file://C:/Users/xxx/ThingML/testJar/src/main/resources/tests/StateMachine/testCompositeStates.thingml"` seems to work. Just try on Linux if `file://` works.

**Comment by Lyadis** [comment]
No it doesn't seem to.

**Comment by brice-morin** [comment]
OK, then `import "/C:/Users/xxx/ThingML/testJar/src/main/resources/tests/StateMachine/testCompositeStates.thingml"` seems to work on Windows. So it is basically to replace `\` with `/` and add a leading `/` if it is not there. That should be generic enough to work everywhere.
