### ISSUE TITLE
Specifying the return type of external expressions

### ISSUE THREAD

**Issue by jakhog** [SINTEF-9012/ThingML#149]
The TypeChecker is currently unable to determine the type of external expressions, which in many cases means that the compiler spits out a lot of warnings saying messages are sent, functions are called or variables assigned with values/expressions which cannot be typed. In large projects, this means that warnings that you actually care about is clouded by all these type checker warnings.

To make the TypeChecker more useful, I suggest that a way to specify the return type of external expressions is added to the ThingML language.

At least for Java and C, the expressions could simply be wrapped with a casting expression, which would leave the actual type checking to the native compilers (which makes sense since the external expressions are written in the native language, so the user should know how to deal with it).

Perhaps something as simple as putting the ThingML type in parentheses just before the expression (like C or Java type casting)?

**Comment by ffleurey** [comment]
done, now the type checker should be updated
