### ISSUE TITLE
Region.getSubstate() ???

### ISSUE THREAD

**Issue by brice-morin** [SINTEF-9012/ThingML#158]
It seems `Region.getSubstate()` does not exist anymore in the new metamodel (XText). Which class now contains sub-state?

It seems that `Region.getSubstate()` is one of the last blocking issue before we can re-try the Java and JavaScript compilers...

**Comment by jakhog** [comment]
It seems like it was moved (back) to the `CompositeState` class...

**Comment by brice-morin** [comment]
Yes. But what is a region now in the metamodel. Seems like we can just get and set an initial state, but no more. 

Also, sessions used to be states. Not anymore.

I guess we have to think and decide a few things on this part of the metamodel (the rest is somehow similar modulo minor adjustments) before we can finalize the migration of compilers...

**Comment by brice-morin** [comment]
OK, it pretty much migrated everything I could in all compilers and plugins. Still, we have a problem with Composite, Region and Sessions. I made a picture suggesting refactorings.

![thingml_region_session](https://cloud.githubusercontent.com/assets/576169/23058311/ac7a530e-f4f4-11e6-9a77-9386044bf8dc.png)

**Comment by ffleurey** [comment]
Solved by a complete refactoring of the metamodel around states, sessions and regions.
