### ISSUE TITLE
Default values on properties

### ISSUE THREAD

**Issue by ffleurey** [SINTEF-9012/ThingML#2]
It would be useful to have initialization on properties definition. I am thinking of making it mandatory (like in scala).

**Comment by Lyadis** [comment]
Is this discussion still ongoing?

**Comment by brice-morin** [comment]
Well, we still do not have mandatory initialization... but we should now be careful not to break compatibility e.g. with models from HEADS partner by making something mandatory that used to be optional (unless they initialize their properties).
