### ISSUE TITLE
Serial in Arduino 1.0.1

### ISSUE THREAD

**Issue by brice-morin** [SINTEF-9012/ThingML#20]
It seems Arduino has changed quite a lot between 0022 and 1.0.1 regarding the way the deal with serial communication... See http://arduino.cc/en/Main/ReleaseNotes

The same ThingML program (using Serial communication on Arduino) compiled with Arduino 0022 and 1.0.1 provides very different results when reading bytes from RxTx on the Java side. (However, it seems some good tools like Putty do not really see any difference... so there might be a way to properly configure RxTx).

For now I am sticking with 0022 for my experiments.

**Comment by Lyadis** [comment]
May be should just let go the support for arduino IDE versions that out of date. I don't think many people are still using it, And as long as we document wich version we support, I think it's no big deal to forget about the old one.

**Comment by brice-morin** [comment]
Yes, I guess that issue solved itself, in a way
