### ISSUE TITLE
BIG_ENDIAN and LITTLE_ENDIAN, Signed and Unsigned

### ISSUE THREAD

**Issue by brice-morin** [SINTEF-9012/ThingML#21]
It seems the low-level encoding of datatypes (BIG_ENDIAN, LITTLE_ENDIAN) is not uniform. Globally, it seems we favor BIG_ENDIAN (which is BTW the default encoding for Java). It works OK when we exchange data between Arduino and Scala. But the CoAP generated servers seems to use LITTLE_ENDIAN....

The CoAP compiler should be updated.

Also, we should think about how signed/unsigned C types map to Java types

**Comment by brice-morin** [comment]
@Lyadis do we assume the serialization and network plugins solve that?

**Comment by Lyadis** [comment]
We can assume that it will (probably not that it does)...
