### ISSUE TITLE
Multiple connectors and group

### ISSUE THREAD

**Issue by brice-morin** [SINTEF-9012/ThingML#26]
It seems impossible to have multiple connectors targeting the same instance within a group...

**Comment by vassik** [comment]
I get the same issue, here is the code snip where i get this:
```
//alarmpsm.thingml
configuration fragment AlarmPIMMQTTConfig {
	instance mqttalarmpsm : MQTTClientPSM	
	instance alarmpim : AlarmPim

	connector alarmpim.mqttport => mqttalarmpsm.mqttport
}

//alarmpim.thingml
configuration AlarmGatewayTest
  @output_folder "/home/tmp/"
  @add_c_libraries "paho-mqtt3a tmlmqtt cson"
{
	group alarmmqttpsm : AlarmPIMMQTTConfig	
	instance gateway : GatewayImpl
	
	connector gateway.alarmSirene => alarmmqttpsm.alarmpim.sirene
	connector gateway.alarmAlert => alarmmqttpsm.alarmpim.alert
	connector gateway.alarmMonitor => alarmmqttpsm.alarmpim.monitor
}
```

for the second and third connector in AlarmGatewayTest, the following error pops up

Description	Resource	Path	Location	Type
An expection occured while resolving the proxy for: EMFTEXT_INTERNAL_URI_FRAGMENT_14_alert. (java.lang.NullPointerException)	gateway_g2_test_config.thingml	/ThingMLSamples/thingmlg2demo	line 22	EMFText Problem

**Comment by brice-morin** [comment]
@Lyadis this one you should look into in priority.

**Comment by ffleurey** [comment]
Seems like an EMFText issue... do we have good motivations for keeping this group concept or should we re-think it a bit? @Lyadis is going to write a few tests.

**Comment by brice-morin** [comment]
Well, it is useful e.g in the case of Anatoly, as it makes it easy to include a pre-configured PSM fragment into a PIM model, without polluting the model with the PSM details. Then it is more in the methodology we should advise people to use it wisely.

**Comment by Lyadis** [comment]
After some tests, it appears that the problem happens only when the fragment configuration is in a separated file.
Indeed when both configurations are in the same file, the compiler doesn't complain.

**Comment by brice-morin** [comment]
Ok. Can you create proper test cases for both cases, so that we can have them included in the test suite.
