### ISSUE TITLE
add support in ThingML to create a make file with includes for compiler ( '-I' option) for the C++ and C generators

### ISSUE THREAD

**Issue by vassik** [SINTEF-9012/ThingML#32]
should be supported if we want to use third party libs. It is better then carrying along all H files every time

**Comment by brice-morin** [comment]
@Lyadis what is the status here?

**Comment by Lyadis** [comment]
It is fixed. 
You can use the annotation `@add_c_libraries "myLib"` on a thing. It will add `-l myLib` to the makefile.
You can also use `@add_c_libraries_rep "path/to/my/rep"` to indicate a path to include for .so (it will add `-L path/to/my/rep` to the makefile)  and `@add_c_flags "myflag"` to add flags, and `@add_c_directives "myDirective"` to add `-D myDirective`.
