### ISSUE TITLE
String parameters produce compilation error in Arduino

### ISSUE THREAD

**Issue by brice-morin** [SINTEF-9012/ThingML#38]
When using the LCD_screen, the compilation of:

```
required port Display
	{
		sends initDisplay, refreshDisplay, setDisplay
  // with initDisplay defined as: message initDisplay (id : UInt8, title : String, unit : String, initValue : Integer, minValue : Integer, maxValue : Integer);
	}
```
produces compilation error in the generated Arduino code:

```
// parameter title
ptr_union_t __ptrunion_title; //here is the faulty line
__ptrunion_title.pointer = (void*)title;
_fifo_enqueue( __ptrunion_title.buffer[0] );
_fifo_enqueue( __ptrunion_title.buffer[1] );
```

the error says:
```
BlinkArduino.cpp: In function 'void enqueue_Meteo_send_Display_initDisplay(Meteo_Instance*, uint8_t, char*, char*, int, int, int)':
BlinkArduino:1608: error: 'ptr_union_t' was not declared in this scope
```

Note that it works when we add the ```@sync_send "true"``` annotation (which is probably better, but still, it should work without that annotation).

**Comment by brice-morin** [comment]
Seems like @Lyadis is facing the same (or very similar) problem. What is the strategy here, Dr @ffleurey ?

**Comment by Lyadis** [comment]
@sync_send "true" work indeed.

**Comment by ffleurey** [comment]
The strategy is to only allow pointers when we do synchronous calls (so with the @sync_send "true"). For async messages it is not allowed and we should probably report it as en error earlier. The point is to never serialize pointers because they typically will not make sense when de-serialized.

**Comment by brice-morin** [comment]
Does it mean we should refactor the metamodel to split datatype into primitive type and pointers? So that it would be easier to make a checker (otherwise it is more like a hack to guess whether datatypes are primitive or pointers). Also, should the @sync_send be promoted as a proper concept?

**Comment by ffleurey** [comment]
Good questions :-) I think that the sync send probably deserves to be promoted. In terms of the pointers/value issues, it is quite specific to the target platforms so maybe some annotation can be a good start. What we need it to initialize a proposer "checker framework" to allow easily adding individual checks.
