### ISSUE TITLE
"Compile-time" properties

### ISSUE THREAD

**Issue by ffleurey** [SINTEF-9012/ThingML#4]
Currently all the properties are dynamic but we could have the equivalent of Java final attributes (or scala val) which value would be fixed at compile time. The value of these properties could be used by the code generators in order to optimize the generated code by, for example, substituting the values.

**Comment by brice-morin** [comment]
Yes, this would allow having configurable fixed-sized arrays in C (currently the only test not passing...), which can be quite useful for some use cases.

**Comment by brice-morin** [comment]
@Lyadis
