### ISSUE TITLE
concept of internal communication wanted!

### ISSUE THREAD

**Issue by vassik** [SINTEF-9012/ThingML#44]
It seems like we need something that allows passing and receiving messages internally. It is possible do it by defining two ports and connecting them together. It looks quite complex and cluttering a thing. We do not use these ports for communication with other things so we should not expose them publicly. Binding these ports looks redundant and we usually forget this.

We suggest having sort of 'trigger' concept which acts as a couple of ports connected together by default. We should be able to generate more efficient code for the internal communication.

Example:

Expected
```
thing X includes Xmessages {
        
    trigger trigger_name message_name;
    
    statechart behavior init Start {
        ...
        state Start{
          on entry do
            print "Srating...\n"
            b = getSomethig()
            trigger_name!message_name(b)
          end
                    
          transition->Something
          event e : trigger_name?message_name
          .....
        }
       ......
    }
}
```

Actual (current workaround)
```
thing X includes Xmessages {
    provided port sendportinternal {
           sends message_name
    }
   required port receiveportinternal {
           receives message_name
    }
    
    statechart behavior init Start {
        ...
        state Start{
          on entry do
            print "Srating...\n"
            b = getSomethig()
            sendportinternal!message_name(b)
          end
                    
          transition->Something
          event e : receiveportinternal?message_name
          .....
        }
       ......
    }
}
configuration Some {
    instance x:X
    connector x.receiveportinternal => x.sendportinternal // we usually forget this
}
```

Note:
Franck you can reassign to anyone you want if you think this feature makes sense )))

**Comment by brice-morin** [comment]
Yes, some people in the HEADS project also need internal port HEADS-project/heads_ide#70
