### ISSUE TITLE
C compiler does not manage precedence in event comsumption in composite states

### ISSUE THREAD

**Issue by acartero** [SINTEF-9012/ThingML#46]
Substates should have precedence over superstates to consume events : http://en.wikipedia.org/wiki/UML_state_machine#Event_deferral .

There is currently no precedence rule in C, the test "testCompEventCapture" gives an example of such behaviour.

**Comment by brice-morin** [comment]
I guess this is solved, isn't it @ffleurey  and @Lyadis ?
