### ISSUE TITLE
Eclipse bundles for dropins have unresolved deps

### ISSUE THREAD

**Issue by ffleurey** [SINTEF-9012/ThingML#5]
The ANTLR plugin should be bundled with the parse to avoid having to install EMFText runtime to use ThingML. Also, as much as possible we should use package deps and not bundle deps. We should also check that all packages are properly exported (at least the CharacterEscaper of the parser is not).

**Comment by brice-morin** [comment]
I guess everything is now OK, since ThingML seems to be properly integrated in HEADS IDE
