### ISSUE TITLE
C compiler produces bad code if the configuration and a thing have the same name

### ISSUE THREAD

**Issue by brice-morin** [SINTEF-9012/ThingML#57]
Basically because the .h and .c files of the configuration or replaced (and do not exist anymore) by the .h and .c files of the thing (or vice versa). So at the end, something is missing resulting in a looooong list of errors when trying to compile the resulting C code.

**Comment by Lyadis** [comment]
The configuration file corresponding to the configuration is now named configuration_name + "_cfg.c".
