### ISSUE TITLE
Arduino compiler makes half-baked optimization

### ISSUE THREAD

**Issue by brice-morin** [SINTEF-9012/ThingML#59]
it seems the arduino compiler (and maybe C too) makes some smart optimization, trying to remove some messages and ports that are not used. So far, so good. The problem is that the associated declarations are removed, but those declarations are still called at some point in the code, causing compilation errors (xxx not declared).

**Comment by brice-morin** [comment]
I guess this is fixed, isn't it @Lyadis ? If so, close the issue

**Comment by Lyadis** [comment]
I hope so!
