### ISSUE TITLE
Port visibility

### ISSUE THREAD

**Issue by brice-morin** [SINTEF-9012/ThingML#63]
We should consider adding the notion of visibility on ports to indicate whether a port is:
- accessible from non-thingML components, which can call (or get notified by) some ThingML code (corresponding to the messages on that port)
- private to ThingML, as this port is only needed for implementation details, and offering it to the outside might actually be undesirable as it might screw up with the internal behavior

This would help generating clean APIs (and coarser-grained component e.g. with Kevoree), which only expose what should be exposed.

I guess we would just need a `public` modifier and nothing if we want the port to be private. 

Currently (e.g. in the MQTT compiler) I rely on an annotation `@public "true"` to tag such ports

**Comment by brice-morin** [comment]
Or, we can assume that a port that is not connected in a configuration should be made visible by default (and up to the C/Java/JS programmer to connect it), and that ports that are connected should be considered as internal/private.

However in some case we might want to expose a port that is connected in the ThingML configuration

**Comment by Lyadis** [comment]
Now that we have the concept of external connector, we also can say that a port connected with an external connector is public, and any other port is private.

**Comment by brice-morin** [comment]
Yes, that makes sense.
