### ISSUE TITLE
Java import in ThingML (Path problem)

### ISSUE THREAD

**Issue by Lyadis** [SINTEF-9012/ThingML#80]
I have this project which contains:

- JavaLib/myClass.java
- Test.thingml 

```
// Test.thingML

datatype myClass
	@java_type "JavaLib.myClass";

thing Test {
	property myA : myClass = 'new JavaLib.myClass('& 3 &');'
	
	statechart TestChart init Init {
		state Init {
			on entry do
				print "[Test] Start"
				''&myA &'.displayA();'
				print "[Test] End"
			end
		}
	}
}

configuration TestCfg {
	instance t : Test
}
```

How do I specify the path of myClass. Because so far, the only way I made it works is puting it in the folder thingml-gen/java/src/main/java or with an absolute path.

**Comment by brice-morin** [comment]
Package your lib in a Maven project that you install locally.

Then in your thing, use the `@maven_dep "JavaLib"` annotation to tell the thing where to find the dependency.

Try that and close the issue if it works :-)

**Comment by Lyadis** [comment]
@maven_dep seems to copy directly its content in the pom.xml between <dependecies></dependecies>

so I need to write it this way, to make it work. Is it the proper way?
```
@maven_dep "

<dependency>
    <groupId>MyGroupeID</groupId>
    <artifactId>MyArtefactID</artifactId>
    <version>0.0.1-SNAPSHOT</version>
</dependency>"
```

**Comment by brice-morin** [comment]
yes indeed

**Comment by lmouline** [comment]
Is it possible to have a syntaxe like : 
@maven_dep "groupID:ArtefactID:Version" ?

And parse it.

**Comment by brice-morin** [comment]
Yes, you can implement that feature, in addition (not in place) of the current one. :-)
