### ISSUE TITLE
Dependencies to old compiles

### ISSUE THREAD

**Issue by lmouline** [SINTEF-9012/ThingML#83]
In the org.thingml.cmd module, there is still a dependency to old compiler (https://github.com/SINTEF-9012/ThingML/blob/master/org.thingml.cmd/pom.xml)

```
<dependency>
            <groupId>org.thingml</groupId>
            <artifactId>org.thingml.compilers</artifactId>
            <version>${project.version}</version>
</dependency>
```

(When I try to fix it I have this error : 
```
 Could not resolve dependencies for project org.thingml:org.thingml.cmd:jar:0.6.0-SNAPSHOT: Could not find artifact org.thingml:compilers:jar:0.6.0-SNAPSHOT in thingml-snapshot (http://maven.thingml.org/thingml-snapshot/)
```

And I don't know how fix this error.)

As a result, your tests might not pass with the new compiler :))

**Comment by brice-morin** [comment]
you should depend from `compilers.registry`, not `compilers`

Note that we will soon get rid of the `Cmd` project, which will be replaced by the commandline.
