### ISSUE TITLE
Annotation @arduino_stdout might not work properly anymore

### ISSUE THREAD

**Issue by Lyadis** [SINTEF-9012/ThingML#84]
from the thingml code:
print "Ping Client Started!\n"

it generated:
// PRINT ERROR: "Ping Client Started!\n"

and no initialisation.

I'll try to fix it, or may be it was decided not to support the annotation anymore?

**Comment by brice-morin** [comment]
Yes, the annotation is probably not handled anymore. But I think it still makes sense to use it. Good that you volunteer to fix it :-)
