### ISSUE TITLE
JAVA - Thing that sends a message to itself doesn't work in some case

### ISSUE THREAD

**Issue by lmouline** [SINTEF-9012/ThingML#88]
```
thing Thing includes Message {
    provided port send {
        sends m1    
    }    
    
    required port receive {
        receives m1    
    }
    
    statechart Statechart init Init {
        state Init {
            on entry send!m1()
            
            internal
            event receive?m1
            action print "OK"    
        }    
    }
}
```

This code doesn't work in JAVA, whereas in JS it works.
However, with the port configuration following : 
```
  required port send {
        sends m1    
    }    
    
    provided port receive {
        receives m1    
    }
```

I guess this bug is created by JASM library.

**Comment by brice-morin** [comment]
OK, I refactored the JASM library. I was not satisfied anyway with the way Connectors were made (it was too much logic going on whenever we wanted to change a message. Now everything is simplified. Ports can basically listens to other ports (on other Component/Thing, or on the same thing, it does not matter).
