### ISSUE TITLE
JS Tests failed

### ISSUE THREAD

**Issue by lmouline** [SINTEF-9012/ThingML#91]
When I execute the JS test with a fresh installation I get this error:
```
Enet.js:633
    throw new TypeError('invalid data');
          ^
TypeError: invalid data
    at Socket.write (net.js:633:11)
    at /tmp/ThingML/org.thingml.tests/target/tmp/_javascript/TestOnEntry/TestDumpJS.js:57:16
```

According to my first quick search, the reason may be explained here: https://stackoverflow.com/questions/26851860/stdout-write-with-nodejs

**Comment by brice-morin** [comment]
Ah yes, I did not re-launch the tests after I made this simple change... I guess you can fix it, concatenating with an empty string or something to make sure we get a string.
