### ISSUE TITLE
Java generated code use old Jasm Version

### ISSUE THREAD

**Issue by lmouline** [SINTEF-9012/ThingML#92]
JASM has been updated a few days ago. However, the Java generated code still use the old version of the library (and the version on the maven repository is still the old version).

Is it possible to update the Java Compiler and the JASM version on the maven repository?

**Comment by brice-morin** [comment]
Hmmm... I thought I updated the compiler. Do you still have 'new Connector' in the generated Main file?

**Comment by lmouline** [comment]
I am going to check.
But, in the generated code the Things still call the Component.send method. But, its doesn't exist anymore.

**Comment by lmouline** [comment]
Ok the problem becomes from my computer (but not from me ^^)
I have some black magic things  that caused the disappearance of some methods in the Port class...

**Comment by brice-morin** [comment]
Should I call an exorcist?
