### ISSUE TITLE
JAVA - Test does not pass

### ISSUE THREAD

**Issue by lmouline** [SINTEF-9012/ThingML#93]
The test testMultiServerPingTest does not pass in JAVA on a fresh installation. I get this error message:
```
Results :

Failed tests:   testJava(org.thingml.tests.testMultiServerPingTest): Java compiler error: P does not match P1P2P2P2P1 for input 12221 (12221)
```

**Comment by brice-morin** [comment]
Ok, not a total surprise, but not a total problem neither. I modified the way ports and connectors work. I'll look into that.
